dataset:
  _target_: datasets.IRMColoredMNIST
  root: /research/hal-gaudisac/Diffusion/image_gen/data/IRMColoredMNIST
dataloader:
  batch_size: 256
  num_workers: 4
  persistent_workers: True
trainer:
  max_epochs: 100
  accelerator: 'gpu'
  log_every_n_steps: 10
  gradient_clip_val: 1.0