dataset:
  target: gmm.GaussianMixtureDataset
  num_classes: 8
  num_samples: 1000
  num_features: 2
  dataloader:
    train_batch_size: 256
    test_batch_size: 128
    num_workers: 4
    persistent_workers: True
logging:
  directory: lightning_logs
diffusion:
  target: score.DDPMProcess
  noise_schedule: 'linear'
  num_steps: 500
  t_span: (0, 1)
  latent_dim: 64
  latent_method:
    target: vae.VAE
    train: True
    num_epochs: 100
    lr: 1e-3
  model:
    name: models.Time
    num_epochs: 100





  





